services:
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./front:/app  # Monta o código-fonte do frontend
      - /app/node_modules
    restart: always

  backend:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=apibd
      - MYSQL_PASSWORD=passmaisa
      - MYSQL_DATABASE=bd_maisa
    volumes:
      - ./back:/app  # Monta o código-fonte do backend
      - /app/node_modules  # Mantém node_modules dentro do container
    restart: always

  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passmaisa
      - MYSQL_DATABASE=bd_maisa
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
