services:
  frontend:
    build: ./front
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./front:/app
      - /app/node_modules
    restart: always

  backend:
    build: ./back
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=apibd
      - MYSQL_PASSWORD=passmaisa
      - MYSQL_DATABASE=bd_maisa
    volumes:
      - ./back:/app
      - /app/node_modules
    restart: always
    command: sh -c "npx prisma db pull && npx prisma generate && npm run dev"


  mysql:
    build: ./mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=passmaisa
      - MYSQL_DATABASE=bd_maisa
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  mysql_data:
