services:
  frontend:
    build: ./front
    ports:
      - "5173:5173"  # Redireciona a porta 8080 para o Vite (5173)
    depends_on:
      - backend
    volumes:
      - front_volume:/app/node_modules
    restart: always

  backend:
    build: ./back
    ports:
      - "3000:3000"  # Mantém a porta padrão do NestJS
    depends_on:
      - mysql
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=apibd
      - MYSQL_PASSWORD=passmaisa
      - MYSQL_DATABASE=bd_maisa
    volumes:
      - back_volume:/app/node_modules
    restart: always

  mysql:
    build: ./mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=passmaisa
      - MYSQL_DATABASE=bd_maisa
    volumes:
      - mysql_data:/var/lib/mysql
    restart: always

volumes:
  front_volume:
  back_volume:
  mysql_data:
